# Generated by Django 4.2.5 on 2023-09-05 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articlescopes_scopes_articlescopes_scope'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scopes',
            name='articles',
        ),
    ]
