# Generated by Django 4.2.5 on 2023-09-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_remove_scopes_articles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleScopes',
            new_name='Scope',
        ),
        migrations.RenameModel(
            old_name='Scopes',
            new_name='Tag',
        ),
        migrations.RenameField(
            model_name='scope',
            old_name='scope',
            new_name='tag',
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(related_name='articles', through='articles.Scope', to='articles.tag'),
        ),
    ]
